### ISSUE TITLE
[Question] turn off clustering

### ISSUE THREAD

**Issue by r4ptus** [bpillon/google_maps_cluster_manager#9] opened 2020-07-21 10:25 UTC
is it possible to turn off clustering at a specific zoom level?

**Comment by JayPerfetto** [comment] 2020-08-13 17:26
+1

**Comment by BrutalCoding** [comment] 2020-08-25 04:25
Duplicate of https://github.com/bpillon/google_maps_cluster_manager/issues/4

**Comment by bpillon** [comment] 2020-10-08 11:59
Closed. See original #4, I'll implement it soon

**Closed by bpillon** 2020-10-08 11:59 UTC
